### ISSUE TITLE
Implement LaunchScreen and WriteScreen with Navigation and Animation in React Native

### ISSUE THREAD

**Issue by smaarmstrong** [lilrobo/CrateNative#2]
### Issue: Implement `LaunchScreen` and `WriteScreen` with Navigation and Animation in React Native

**Description:**
We need to create two screens (`LaunchScreen` and `WriteScreen`) in React Native to replicate the functionality in SwiftUI. The app will initially display an image on the `LaunchScreen`, which will then transition to `WriteScreen` after a delay. This functionality includes a fade animation for a smooth effect during the transition.

---

### Task Outline:

1. **Set Up Navigation**: 
   - Use React Navigation to manage transitions between `LaunchScreen` and `WriteScreen`.
   - Implement `createStackNavigator` to define screen navigation flow.

2. **Create `LaunchScreen`**:
   - Show an image (`launchImage`) that will be displayed for 2.5 seconds.
   - Apply a fade animation using `Animated` from React Native to smoothly fade in/out the image.
   - After the delay, navigate to `WriteScreen`.

3. **Create `WriteScreen`**:
   - Display a simple message or content to confirm the transition from `LaunchScreen`.

---

#### 1. **App.tsx** – Main Application File

Set up navigation and define the stack navigator to manage transitions between `LaunchScreen` and `WriteScreen`.

```tsx
import React from 'react';
import { NavigationContainer } from '@react-navigation/native'; 
import { createStackNavigator } from '@react-navigation/stack';
import LaunchScreen from './LaunchScreen';
import WriteScreen from './WriteScreen';

const Stack = createStackNavigator();

const App = () => {
  return (
    <NavigationContainer>
      <Stack.Navigator initialRouteName="Launch">
        <Stack.Screen name="Launch" component={LaunchScreen} />
        <Stack.Screen name="Write" component={WriteScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
};

export default App;
```

#### 2. **LaunchScreen.tsx** – Initial Screen

This screen displays an image for 2.5 seconds, after which it navigates to `WriteScreen`. A fade-in animation is used to transition smoothly.

```tsx
import React, { useState, useEffect } from 'react';
import { View, Image, Animated, StyleSheet } from 'react-native';

type Props = {
  navigation: any;
};

const LaunchScreen: React.FC<Props> = ({ navigation }) => {
  const [isWriteScreenActive, setIsWriteScreenActive] = useState(false);
  const fadeAnim = new Animated.Value(0);

  useEffect(() => {
    const timer = setTimeout(() => {
      setIsWriteScreenActive(true);
      navigation.replace('Write');
    }, 2500);

    return () => clearTimeout(timer);
  }, [navigation]);

  useEffect(() => {
    if (isWriteScreenActive) {
      Animated.timing(fadeAnim, {
        toValue: 1,
        duration: 500,
        useNativeDriver: true,
      }).start();
    }
  }, [isWriteScreenActive]);

  return (
    <View style={styles.container}>
      <Animated.View style={[styles.imageContainer, { opacity: fadeAnim }]}>
        <Image
          source={{ uri: 'https://yourimageurl.com/launch-image.jpg' }}
          style={styles.launchImage}
        />
      </Animated.View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  launchImage: {
    width: 300,
    height: 300,
    resizeMode: 'contain',
  },
});

export default LaunchScreen;
```

#### 3. **WriteScreen.tsx** – Secondary Screen

This screen is displayed after the transition from `LaunchScreen`.

```tsx
import React from 'react';
import { View, Text, StyleSheet } from 'react-native';

const WriteScreen = () => {
  return (
    <View style={styles.container}>
      <Text style={styles.text}>This is the WriteScreen</Text>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  text: {
    fontSize: 20,
    fontWeight: 'bold',
  },
});

export default WriteScreen;
```

---

### Recommendations:

1. **Use Screens for Navigation**:
   - The views have been organized as `LaunchScreen` and `WriteScreen` to align with React Navigation terminology.
   - This approach makes it easy to scale the app, add more screens, and manage navigation centrally.

2. **React Navigation for Transitions**:
   - React Navigation is used to transition from `LaunchScreen` to `WriteScreen` after a delay.
   - The `navigation.replace` method is used to prevent the user from returning to `LaunchScreen` after navigating to `WriteScreen`.

3. **Fade Animation for Visual Effect**:
   - The `Animated` library is used to apply a fade animation to the launch image for a smooth transition.
   - This setup can be extended to add more complex animations if needed.

### Acceptance Criteria:

- [ ] `LaunchScreen` displays an image for 2.5 seconds before navigating to `WriteScreen`.
- [ ] A fade animation is applied to the image in `LaunchScreen`.
- [ ] `WriteScreen` is displayed with a text confirmation after the transition.
- [ ] The user cannot navigate back to `LaunchScreen` once on `WriteScreen`.
