### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by smaarmstrong** [lilrobo/CrateNative#3]
- [ ] Primary URL input field
- [ ] + Sign for Adding additional Input-Field/Types
- [ ] Write Button
- [ ] Figure out "Action Sheet Share" as applicable
- [ ] Look into buying a cheap Google Pixel for testing.
